# sonata_classification.yml

sonata_classification:
    # ...

doctrine:
    orm:
        entity_managers:
            default:
                mappings:
#                    SonataClassificationBundle: ~
                    ApplicationSonataClassificationBundle: ~